# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customize atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "LivlyBear"
description:	       "a Jekyll theme for running a blog"
author:              "JIWAN YE"

# RSS 2.0 can be used instead of Atom by uncomment following two lines
#feed:
#  path: rss-feed.xml
